baseURL = "www.kathrynlwhelan.com"
languageCode = "en-us"
DefaultContentLanguage = "en-us"
title = "Kathryn Whelan"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true


pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Kathryn Whelan"
author = "Kathryn Whelan"
#copyright = "2020-2021"
description = """
Software Engineer
Looking For Mobile Development Opportunities
"""
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = ["custom.css"]
# example ["js/custom.js"]
customJs = []
mainSections = []
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
displayMode = "dark"
disableThemeSwitcher = false
postSectionName = "blog"
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/kathrynlwhelan/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/katiewhelan"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:klwhelan@gmail.com"

[menu]

  [[menu.main]]
  name = "About"
  weight = 100
  identifier = "about"
  url = "/"

  [[menu.main]]
  name = "Project"
  weight = 200
  identifier = "project"
  url = "/project/"

  [[menu.main]]
  name = "App in Action"
  weight = 300
  identifier = "appInAction"
  url = "/appInAction/"

  [[menu.main]]
  name = "Blog"
  weight = 400
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "What's Next"
  weight = 500
  identifier = "next"
  url = "/next/"

  [[menu.main]]
  name = "Resume"
  weight = 600
  identifier = "resume"
  url = "/resume/"
